<?php
/**
 * @file
 * Basic template to render form row.
 *
 * @var $element         \Zend\Form\Element
 * @var $label           string
 * @var $labelAttributes array
 * @var $labelPosition   string
 * @var $renderErrors    bool
 */

$wrapper = $element->getOption('wrapper_class');
$glyphicon = $element->getOption('glyphicon');
$feedback = $element->getOption('feedback');
$wrapLabel = $element->getLabelOption('always_wrap');
$type = $element->getAttribute('type');
?>
<?php if ($type !== 'hidden'): ?><div class="form-group<?php if ($feedback): ?> has-feedback<?php endif; ?>"><?php endif; ?>
    <?php if (!$wrapLabel && $label && $labelPosition === 'prepend'): ?>
        <?php echo $this->formLabel($element); ?>
    <?php endif; ?>

    <?php if ($wrapper && $type !== 'hidden'): ?><div class="<?php echo $this->escapeHtmlAttr($wrapper); ?>"><?php endif;?>
        <?php if ($wrapLabel): ?>
            <?php echo $this->formLabel($element, $this->formElement($element), $labelPosition); ?>
        <?php else: ?>
            <?php echo $this->formElement($element); ?>
        <?php endif; ?>

        <?php if ($glyphicon): ?>
            <span class="glyphicon glyphicon-<?php echo $this->escapeHtmlAttr($glyphicon); ?><?php if ($feedback): ?> form-control-feedback<?php endif; ?>"></span>
        <?php endif; ?>

        <?php if ($element->getOption('help')): ?>
            <p class="help-block"><?php echo $element->getOption('help'); ?></p>
        <?php endif; ?>

        <?php if ($renderErrors): ?>
            <?php echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="has-error"><p class="help-block">')
                ->setMessageSeparatorString('</p><p class="help-block">')
                ->setMessageCloseString('</p></div>')
                ->render($element); ?>
        <?php endif; ?>
    <?php if ($wrapper && $type !== 'hidden'): ?></div><?php endif;?>

    <?php if (!$wrapLabel && $label && $labelPosition === 'append'): ?>
        <?php echo $this->formLabel($element); ?>
    <?php endif; ?>
<?php if ($type !== 'hidden'): ?></div><?php endif; ?>
