<?php
/**
 * @file
 * Basic template to render form row.
 *
 * @var $element         \Zend\Form\Element
 * @var $label           string
 * @var $labelAttributes array
 * @var $labelPosition   string
 * @var $renderErrors    bool
 */
?>
<div class="form-group">
    <?php if ($label): ?>
        <?php print $this->formLabel($element); ?>
    <?php endif; ?>

    <div class="<?php print $this->escapeHtmlAttr($element->getOption('wrapper_class')); ?>">
        <?php print $this->formElement($element); ?>

        <?php if ($element->getOption('help')): ?>
            <p class="help-block"><?php print $element->getOption('help'); ?></p>
        <?php endif; ?>

        <?php if ($renderErrors): ?>
            <?php print $this->formElementErrors()
                ->setMessageOpenFormat('<div class="has-error"><p class="help-block">')
                ->setMessageSeparatorString('</p><p class="help-block">')
                ->setMessageCloseString('</p></div>')
                ->render($element); ?>
        <?php endif; ?>
    </div>
</div>
