<?php
/**
 * @file
 *
 * @var \User\Form\LoginForm $form
 */

$form->prepare();
?>
<p class="login-box-msg"><?php echo $this->translate('Sign in to start your session'); ?></p>

<?php echo $this->form()->openTag($form->removeAttribute('class')); ?>
    <?php echo $this->formRow($form->get('email')) ?>

    <?php echo $this->formRow($form->get('password')) ?>

    <div class="row">
        <div class="col-xs-8">
            <div class="checkbox icheck">
                <?php echo $this->formRow($form->get('remember_me'), 'append'); ?>
            </div>
        </div>
        <div class="col-xs-4">
            <?php echo $this->formRow($form->get('submit')->setAttribute('class', 'btn btn-primary btn-block btn-flat')); ?>
        </div>
    </div>

    <?php echo $this->formRow($form->get('csrf')); ?>
<?php echo $this->form()->closeTag(); ?>

<?php
$this->inlineScript()->captureStart();
echo <<<JS
(function ($) {
    $(document).ready(function() {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
    });
})(jQuery);
JS;
$this->inlineScript()->captureEnd();
?>
