<?php
/**
 * @file
 *
 */
?>
<p class="login-box-msg"><?php echo $this->translate('Sign in to start your session'); ?></p>

<form action="<?php echo $this->url('admin'); ?>" method="post">
    <div class="form-group has-feedback">
        <input type="email" class="form-control" placeholder="Email">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
    </div>
    <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="Password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
    </div>
    <div class="row">
        <div class="col-xs-8">
            <div class="checkbox icheck">
                <label><input type="checkbox"> <?php echo $this->translate('Remember Me'); ?></label>
            </div>
        </div>
        <div class="col-xs-4">
            <button type="submit" class="btn btn-primary btn-block btn-flat"><?php echo $this->translate('Sign In'); ?></button>
        </div>
    </div>
</form>

<div class="social-auth-links text-center">
    <p><?php echo $this->translate('- OR -'); ?></p>
    <a href="#" class="btn btn-block btn-social btn-facebook btn-flat">
        <i class="fa fa-facebook"></i> <?php echo $this->translate('Sign in using Facebook'); ?>
    </a>
    <a href="#" class="btn btn-block btn-social btn-google btn-flat">
        <i class="fa fa-google-plus"></i> <?php echo $this->translate('Sign in using Google+'); ?>
    </a>
</div>

<a href="#"><?php echo $this->translate('I forgot my password'); ?></a><br>
<a href="<?php echo $this->url('admin/register'); ?>" class="text-center"><?php echo $this->translate('Register a new membership'); ?></a>

<?php
$this->inlineScript()->captureStart();
echo <<<JS
(function ($) {
    $(document).ready(function() {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
    });
})(jQuery);
JS;
$this->inlineScript()->captureEnd();
?>

