<?php
/**
 * @file
 * List of articles.
 *
 * @var $articles \Article\Entity\Article[]
 */
?>

<?php foreach ($articles as $article): ?>
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <a href="<?php print $this->url('article/view', array('id' => $article->getId())); ?>">
                    <img src="<?php print $this->serverUrl() . '/files/article/' . $article->getThumbnail()->getFilename(); ?>" />
                </a>

                <div class="caption">
                    <h3>
                        <a href="<?php print $this->url('article/view', array('id' => $article->getId())); ?>">
                            <?php print $this->escapeHtml($article->getTitle()); ?>
                        </a>
                    </h3>

                    <p><?php print $article->getText(); ?></p>

                    <p><a class="btn btn-link" role="button" href="<?php print $this->url('article/view', array('id' => $article->getId())); ?>"><?php print $this->escapeHtml('Read more'); ?></a></p>
                </div>
            </div>
        </div>
    </div>
<?php endforeach; ?>
