<?php
/**
 * @file
 * List of articles.
 *
 * @var $articles \Article\Entity\Article[]
 */
?>

<div class="row">
<?php foreach ($articles as $article): ?>
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <?php if ($article->hasThumbnail()): ?>
            <a href="<?php print $this->url('article/view', array('id' => $article->getId())); ?>">
                <img src="<?php print $this->serverUrl() . '/files/' . $article->getThumbnail()->getFilename(); ?>" />
            </a>
            <?php endif; ?>

            <div class="caption">
                <h3>
                    <a href="<?php print $this->url('article/view', array('id' => $article->getId())); ?>">
                        <?php print $this->escapeHtml($article->getTitle()); ?>
                    </a>
                </h3>

                <p><?php print $article->getText(); ?></p>

                <p><a class="btn btn-link" role="button" href="<?php print $this->url('article/view', array('id' => $article->getId())); ?>"><?php print $this->escapeHtml('Read more'); ?></a></p>
            </div>
        </div>
    </div>
<?php endforeach; ?>
</div>
