<?php
/**
 * @file
 * Article view template.
 *
 * @var $article \Article\Entity\Article
 */

$this->headTitle($this->escapeHtml($article->getTitle()));
?>
<h1><?php print $this->escapeHtml($article->getTitle()); ?></h1>

<div class="thumbnail">
    <a href="<?php print $this->serverUrl() . '/files/' . $article->getThumbnail()->getFilename(); ?>">
        <img src="<?php print $this->serverUrl() . '/files/' . $article->getThumbnail()->getFilename(); ?>" />
    </a>
</div>

<?php print $article->getText(); ?>

<p class="metadata">
    <?php printf($this->translate('Posted by %s | on %s'), $this->username($article->getAuthor()), $this->articleMetadata($article)); ?>
    <?php if ($this->identity()): ?>
        | <a class="warning" role="button" href="<?php print $this->url('article/edit', array('id' => $article->getId())); ?>"><?php print $this->translate('Edit'); ?></a>
    <?php endif; ?>
</p>
