<?php
/**
 * @file
 * List of articles.
 *
 * @var $articles \Article\Entity\Article[]
 */
?>

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"></h3>

                <div class="box-tools">
                    <div class="input-group">
                        <input type="text" name="search" class="form-control input-sm pull-right" placeholder="Search">

                        <div class="input-group-btn">
                            <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="box-body table-responsive no-padding">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th><?php echo $this->translate('ID'); ?></th>
                        <th><?php echo $this->translate('Image'); ?></th>
                        <th><?php echo $this->translate('Title'); ?></th>
                        <th><?php echo $this->translate('User'); ?></th>
                        <th><?php echo $this->translate('Date'); ?></th>
                    </tr>
                    </thead>

                    <tbody>
                    <?php foreach ($articles as $article): ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($article->getId()); ?></td>
                            <td>
                                <a href="<?php echo $this->url('admin/article/view', array('id' => $article->getId())); ?>">
                                    <img width="80px" src="<?php echo $this->serverUrl() . '/files/' . $article->getThumbnail()->getFilename(); ?>"/>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url('admin/article/view', array('id' => $article->getId())); ?>">
                                    <?php echo $this->escapeHtml($article->getTitle()); ?>
                                </a>
                            </td>
                            <td>
                                <a href="<?php echo $this->url('admin/article/view', array('id' => $article->getAuthor()->getId())); ?>">
                                    <?php echo $this->escapeHtml($article->getAuthor()->getFullName()); ?>
                                </a>
                            </td>
                            <td><?php echo $this->escapeHtml($article->getCreated()->format('d-m-Y h:i:s')); ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
